version: '3.8'
services:
  db:
    image: postgres:16  # Specify a more precise version
    container_name: jobseeker_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${JOBSEEKER_DB_USERNAME}
      POSTGRES_PASSWORD: ${JOBSEEKER_DB_PASSWORD} # Use an environment variable
      POSTGRES_DB: ${JOBSEEKER_DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

networks:
  backend:
    driver: bridge

