"""better institutions

Revision ID: 0b7a45d0d21e
Revises: d8d96fbd7e8c
Create Date: 2024-06-11 14:02:48.560448

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0b7a45d0d21e'
down_revision = 'd8d96fbd7e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('employees', sa.Integer(), nullable=True))
    op.add_column('institutions', sa.Column('tagline', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('institutions', 'followers',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('institutions', 'followers',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('institutions', 'tagline')
    op.drop_column('institutions', 'employees')
    # ### end Alembic commands ###
