"""examples

Revision ID: 1e77b2af209e
Revises: 6722d22c67d0
Create Date: 2024-06-11 19:58:15.613918

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e77b2af209e'
down_revision = '6722d22c67d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cover_letter_paragraph_examples',
    sa.Column('comparison_id', sa.Integer(), nullable=True),
    sa.Column('paragraph_number', sa.Integer(), nullable=False),
    sa.Column('original_paragraph_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('edited_paragraph_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['user_job_posting_comparisons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_experience_examples',
    sa.Column('comparison_id', sa.Integer(), nullable=True),
    sa.Column('original_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_accomplishments', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('edited_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('edited_accomplishments', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['user_job_posting_comparisons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_experience_examples')
    op.drop_table('cover_letter_paragraph_examples')
    # ### end Alembic commands ###
