"""using ids

Revision ID: 2295ed5a52c8
Revises: 5bfa4b4837ff
Create Date: 2024-06-17 14:31:29.556036

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2295ed5a52c8'
down_revision = '5bfa4b4837ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('seniority_level_id', sa.Integer(), nullable=True))
    op.add_column('job_postings', sa.Column('employment_type_id', sa.Integer(), nullable=True))
    op.add_column('job_postings', sa.Column('experience_level_id', sa.Integer(), nullable=True))
    op.add_column('job_postings', sa.Column('salary_range_id', sa.Integer(), nullable=True))
    op.add_column('job_postings', sa.Column('remote_modality_id', sa.Integer(), nullable=True))
    op.drop_constraint('job_postings_remote_modality_fkey', 'job_postings', type_='foreignkey')
    op.drop_constraint('job_postings_salary_range_fkey', 'job_postings', type_='foreignkey')
    op.drop_constraint('job_postings_employment_type_fkey', 'job_postings', type_='foreignkey')
    op.drop_constraint('job_postings_experience_level_fkey', 'job_postings', type_='foreignkey')
    op.drop_constraint('job_postings_seniority_level_fkey', 'job_postings', type_='foreignkey')
    op.create_foreign_key(None, 'job_postings', 'remote_modalities', ['remote_modality_id'], ['id'])
    op.create_foreign_key(None, 'job_postings', 'experience_levels', ['experience_level_id'], ['id'])
    op.create_foreign_key(None, 'job_postings', 'seniority_levels', ['seniority_level_id'], ['id'])
    op.create_foreign_key(None, 'job_postings', 'salary_range_filters', ['salary_range_id'], ['id'])
    op.create_foreign_key(None, 'job_postings', 'employment_types', ['employment_type_id'], ['id'])
    op.drop_column('job_postings', 'salary_range')
    op.drop_column('job_postings', 'seniority_level')
    op.drop_column('job_postings', 'employment_type')
    op.drop_column('job_postings', 'experience_level')
    op.drop_column('job_postings', 'remote_modality')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('remote_modality', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('job_postings', sa.Column('experience_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('job_postings', sa.Column('employment_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('job_postings', sa.Column('seniority_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('job_postings', sa.Column('salary_range', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.create_foreign_key('job_postings_seniority_level_fkey', 'job_postings', 'seniority_levels', ['seniority_level'], ['id'])
    op.create_foreign_key('job_postings_experience_level_fkey', 'job_postings', 'experience_levels', ['experience_level'], ['id'])
    op.create_foreign_key('job_postings_employment_type_fkey', 'job_postings', 'employment_types', ['employment_type'], ['id'])
    op.create_foreign_key('job_postings_salary_range_fkey', 'job_postings', 'salary_range_filters', ['salary_range'], ['id'])
    op.create_foreign_key('job_postings_remote_modality_fkey', 'job_postings', 'remote_modalities', ['remote_modality'], ['id'])
    op.drop_column('job_postings', 'remote_modality_id')
    op.drop_column('job_postings', 'salary_range_id')
    op.drop_column('job_postings', 'experience_level_id')
    op.drop_column('job_postings', 'employment_type_id')
    op.drop_column('job_postings', 'seniority_level_id')
    # ### end Alembic commands ###
