"""examples

Revision ID: 2e9d50de14c9
Revises: 1e77b2af209e
Create Date: 2024-06-11 20:00:01.582504

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2e9d50de14c9'
down_revision = '1e77b2af209e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
