"""start and end date work experiences

Revision ID: 30b4dfeb53f8
Revises: 5a747b82fc10
Create Date: 2024-06-20 13:56:05.286327

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '30b4dfeb53f8'
down_revision = '5a747b82fc10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_experiences', sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('work_experiences', sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('work_experiences', 'start_year')
    op.drop_column('work_experiences', 'end_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_experiences', sa.Column('end_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('work_experiences', sa.Column('start_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('work_experiences', 'end_date')
    op.drop_column('work_experiences', 'start_date')
    # ### end Alembic commands ###
