"""job postings

Revision ID: 4799c3b14dd3
Revises: 621e433f9718
Create Date: 2024-07-22 14:33:40.856142

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4799c3b14dd3'
down_revision = '621e433f9718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
