"""jobposting queries name

Revision ID: 50018b21a098
Revises: 1c3077bde91d
Create Date: 2024-05-24 13:39:11.393513

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '50018b21a098'
down_revision = '1c3077bde91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_posting_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linkedin_company_id', sa.Integer(), nullable=True),
    sa.Column('salary_range_id', sa.Integer(), nullable=True),
    sa.Column('employment_type_id', sa.Integer(), nullable=True),
    sa.Column('experience_level_id', sa.Integer(), nullable=True),
    sa.Column('remote_modality_id', sa.Integer(), nullable=True),
    sa.Column('time_filter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employment_type_id'], ['employment_types.id'], ),
    sa.ForeignKeyConstraint(['experience_level_id'], ['experience_levels.id'], ),
    sa.ForeignKeyConstraint(['remote_modality_id'], ['remote_modalities.id'], ),
    sa.ForeignKeyConstraint(['salary_range_id'], ['salary_range_filters.id'], ),
    sa.ForeignKeyConstraint(['time_filter_id'], ['time_filters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('jobpostingqueries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobpostingqueries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('keywords', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('linkedin_company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('salary_range_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employment_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experience_level_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remote_modality_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_filter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employment_type_id'], ['employment_types.id'], name='jobpostingqueries_employment_type_id_fkey'),
    sa.ForeignKeyConstraint(['experience_level_id'], ['experience_levels.id'], name='jobpostingqueries_experience_level_id_fkey'),
    sa.ForeignKeyConstraint(['remote_modality_id'], ['remote_modalities.id'], name='jobpostingqueries_remote_modality_id_fkey'),
    sa.ForeignKeyConstraint(['salary_range_id'], ['salary_range_filters.id'], name='jobpostingqueries_salary_range_id_fkey'),
    sa.ForeignKeyConstraint(['time_filter_id'], ['time_filters.id'], name='jobpostingqueries_time_filter_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='jobpostingqueries_pkey')
    )
    op.drop_table('job_posting_queries')
    # ### end Alembic commands ###
