"""balance transactions

Revision ID: 567e22a18d01
Revises: da8304d26287
Create Date: 2024-07-19 22:27:14.779423

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '567e22a18d01'
down_revision = 'da8304d26287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balance_transactions', 'balance_after')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_transactions', sa.Column('balance_after', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
