"""resume pdf

Revision ID: 5a747b82fc10
Revises: dc998764c7a3
Create Date: 2024-06-18 19:14:19.487163

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5a747b82fc10'
down_revision = 'dc998764c7a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
