"""relathionships


Revision ID: 5bfa4b4837ff
Revises: cfc2d849c380
Create Date: 2024-06-12 00:56:23.440380

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5bfa4b4837ff'
down_revision = 'cfc2d849c380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_linkedin_id', 'job_postings', ['linkedin_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_linkedin_id', 'job_postings', type_='unique')
    # ### end Alembic commands ###
