"""job postings optional

Revision ID: 621e433f9718
Revises: 567e22a18d01
Create Date: 2024-07-22 14:11:01.978650

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '621e433f9718'
down_revision = '567e22a18d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
