"""adding institution id to job_postings


Revision ID: 66b4cda02503
Revises: e78e0cc3066b
Create Date: 2024-07-11 17:42:09.946788

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '66b4cda02503'
down_revision = 'e78e0cc3066b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_postings', 'institutions', ['institution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_column('job_postings', 'institution_id')
    # ### end Alembic commands ###
