"""institution industry correct name

Revision ID: 8128f3be6271
Revises: d8e9c357f330
Create Date: 2024-06-05 19:03:29.152681

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8128f3be6271'
down_revision = 'd8e9c357f330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutions', 'indsutry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('indsutry', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
