"""jobpostings

Revision ID: 904f4bd60d19
Revises: 4799c3b14dd3
Create Date: 2024-07-22 14:55:21.794454

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '904f4bd60d19'
down_revision = '4799c3b14dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
