""" job postings to scrape table

Revision ID: 946e63009473
Revises: e2ebb5645f21
Create Date: 2024-07-24 15:07:00.126332

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '946e63009473'
down_revision = 'e2ebb5645f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings_to_scrape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linkedin_job_id', sa.BigInteger(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_scraped', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linkedin_job_id', name='uq_linkedin_job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_postings_to_scrape')
    # ### end Alembic commands ###
