"""is_active on comparison

Revision ID: 9cc4e23d14e3
Revises: cfdef24388d4
Create Date: 2024-06-18 14:39:51.263477

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9cc4e23d14e3'
down_revision = 'cfdef24388d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_job_posting_comparisons', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_unique_constraint('uq_user_id_job_posting_id', 'user_job_posting_comparisons', ['user_id', 'job_posting_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_id_job_posting_id', 'user_job_posting_comparisons', type_='unique')
    op.drop_column('user_job_posting_comparisons', 'is_active')
    # ### end Alembic commands ###
