"""work experience dates divided into year and month


Revision ID: bf1937c24431
Revises: 66b4cda02503
Create Date: 2024-07-18 01:04:04.010554

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bf1937c24431'
down_revision = '66b4cda02503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_experiences', sa.Column('start_year', sa.Integer(), nullable=False))
    op.add_column('work_experiences', sa.Column('start_month', sa.Integer(), nullable=True))
    op.add_column('work_experiences', sa.Column('end_year', sa.Integer(), nullable=True))
    op.add_column('work_experiences', sa.Column('end_month', sa.Integer(), nullable=True))
    op.drop_column('work_experiences', 'start_date')
    op.drop_column('work_experiences', 'end_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_experiences', sa.Column('end_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('work_experiences', sa.Column('start_date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('work_experiences', 'end_month')
    op.drop_column('work_experiences', 'end_year')
    op.drop_column('work_experiences', 'start_month')
    op.drop_column('work_experiences', 'start_year')
    # ### end Alembic commands ###
