"""relathionships


Revision ID: cfc2d849c380
Revises: 2e9d50de14c9
Create Date: 2024-06-11 20:46:30.671894

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cfc2d849c380'
down_revision = '2e9d50de14c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
