"""size ids

Revision ID: cfdef24388d4
Revises: 2295ed5a52c8
Create Date: 2024-06-17 14:35:33.768538

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cfdef24388d4'
down_revision = '2295ed5a52c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('size_id', sa.Integer(), nullable=False))
    op.drop_constraint('institutions_size_fkey', 'institutions', type_='foreignkey')
    op.create_foreign_key(None, 'institutions', 'institution_sizes', ['size_id'], ['id'])
    op.drop_column('institutions', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'institutions', type_='foreignkey')
    op.create_foreign_key('institutions_size_fkey', 'institutions', 'institution_sizes', ['size'], ['id'])
    op.drop_column('institutions', 'size_id')
    # ### end Alembic commands ###
