"""adding html

Revision ID: d8d96fbd7e8c
Revises: 8128f3be6271
Create Date: 2024-06-09 21:27:44.099924

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd8d96fbd7e8c'
down_revision = '8128f3be6271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('html', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'html')
    # ### end Alembic commands ###
