"""jobposting bigint

Revision ID: d8e9c357f330
Revises: 50018b21a098
Create Date: 2024-06-05 16:02:59.073259

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd8e9c357f330'
down_revision = '50018b21a098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_postings', 'company_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job_postings', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('job_postings_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_postings', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('job_postings_id_seq'::regclass)"))
    op.alter_column('job_postings', 'company_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
