"""resume pdf

Revision ID: dc998764c7a3
Revises: 9cc4e23d14e3
Create Date: 2024-06-18 18:54:16.148986

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc998764c7a3'
down_revision = '9cc4e23d14e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_job_posting_comparisons', sa.Column('resume', sa.LargeBinary(), nullable=True))
    op.add_column('user_job_posting_comparisons', sa.Column('cover_letter', sa.LargeBinary(), nullable=True))
    op.drop_column('user_job_posting_comparisons', 'cv_pdf')
    op.drop_column('user_job_posting_comparisons', 'cover_letter_pdf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_job_posting_comparisons', sa.Column('cover_letter_pdf', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('user_job_posting_comparisons', sa.Column('cv_pdf', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('user_job_posting_comparisons', 'cover_letter')
    op.drop_column('user_job_posting_comparisons', 'resume')
    # ### end Alembic commands ###
