"""dimensions api

Revision ID: e2ebb5645f21
Revises: 904f4bd60d19
Create Date: 2024-07-24 14:05:52.982477

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e2ebb5645f21'
down_revision = '904f4bd60d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
