"""linkedin job id

Revision ID: e453da078ac1
Revises: 0b7a45d0d21e
Create Date: 2024-06-11 19:12:07.719062

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e453da078ac1'
down_revision = '0b7a45d0d21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('linkedin_id', sa.Integer(), nullable=True))
    op.alter_column('job_postings', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_postings', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('job_postings', 'linkedin_id')
    # ### end Alembic commands ###
