""" credits renamed to balance

Revision ID: e78e0cc3066b
Revises: 26d431ef33ee
Create Date: 2024-07-03 14:51:15.223820

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e78e0cc3066b'
down_revision = '26d431ef33ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.Float(), nullable=False))
    op.drop_column('users', 'credits')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credits', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###
