name: Apply DB Migrations

on:
  push:
    branches:
      - dev  
    paths:
      - 'backend/app/alembic/**' 


env:
  AWS_REGION: ${{secrets.AWS_REGION}}
  POSTGRES_SERVER: ${{ secrets.POSTGRES_SERVER }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


jobs:
  apply-migrations:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install alembic sqlalchemy psycopg2-binary

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{env.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key : ${{ env.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{env.AWS_REGION}}

    - name: Run Alembic migrations
        # Add other environment variables from your .env file here
      run: |
        cd backend
        alembic upgrade head
    - name: Verify migration
      env:
        PGPASSWORD: ${{ env.POSTGRES_PASSWORD }}
      run: |
        psql -h ${{ env.POSTGRES_SERVER }} -U ${{ env.POSTGRES_USER }} -d ${{ env.POSTGRES_DB }} -c "SELECT version_num FROM alembic_version;"
