name: Apply DB Migrations

on:
  push:
    branches:
      - dev  

jobs:
  apply-migrations:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.19'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Apply Alembic migrations
      env:
        POSTGRES_SERVER: ${{ secrets.POSTGRES_SERVER }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        # Add other environment variables from your .env file here
      run: |
        alembic upgrade head

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-1  # e.g., us-west-2

    # Add additional steps here for deploying your application if needed
