name: Apply DB Migrations

on:
  push:
    branches:
      - dev
env:
  POSTGRES_SERVER: ${{ secrets.POSTGRES_SERVER }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{secrets.AWS_REGION}}



jobs:
  apply-migrations:
    runs-on: self-hosted
    environment: DEV

    steps:
    - name: Install system dependencies
      run: |
        sudo yum update -y
        sudo yum install -y postgresql-devel
        sudo yum install -y postgresql15

    - uses: actions/checkout@v2
    - name: Find python3.10 path
      run: |
        which python3.10

    - name: Set up Python
      run: |
        PYTHON_PATH=$(which python3.10)
        sudo ln -sf $PYTHON_PATH /usr/bin/python
        python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install alembic sqlalchemy psycopg2-binary sqlmodel psycopg python-jose passlib

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{env.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key : ${{ env.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{env.AWS_REGION}}


    - name: Create Database if not exists
      env:
        PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      run: |
        psql -h ${{ secrets.POSTGRES_SERVER }} -U ${{ secrets.POSTGRES_USER }} -p ${{ secrets.POSTGRES_PORT }} -tc "SELECT 1 FROM pg_database WHERE datname = '${{ secrets.POSTGRES_DB }}'" | grep -q 1 || psql -h ${{ secrets.POSTGRES_SERVER }} -U ${{ secrets.POSTGRES_USER }} -p ${{ secrets.POSTGRES_PORT }} -c "CREATE DATABASE ${{ secrets.POSTGRES_DB }}"

    - name: Check Alembic environment Python version
      run: |
        cd backend
        python -c "import sys; print(sys.version)"
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python -m alembic current

    - name: Run Alembic migrations
      run: |
        cd backend
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -R
        echo "PYTHONPATH:"
        echo $PYTHONPATH
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python -m alembic upgrade head
    - name: Verify migration
      env:
        PGPASSWORD: ${{ env.POSTGRES_PASSWORD }}
      run: |
        psql -h ${{ env.POSTGRES_SERVER }} -U ${{ env.POSTGRES_USER }} -d ${{ env.POSTGRES_DB }} -c "SELECT version_num FROM alembic_version;"

        
    - name: Insert initial data
      run: |
        cd backend
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python -c "from app.initial_data import main; main()"     
